cuisine/urls.py
from django.urls import path
from . import views

app_name = 'cuisine'

urlpatterns = [
    path('<int:cuisine_id>', views.cuisine_detail, name='cuisine_detail'),
    path('pub', views.pub_comment, name='pub_comment'),
    path('search', views.search, name='search'),
    path('favor/<int:cuisine_id>', views.favor_cuisine, name='favor_cuisine'),
    path('eaten/<int:cuisine_id>', views.eaten_cuisine, name='eaten_cuisine'),
    path('recommend', views.recommend, name='recommend'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('map', views.map, name='map'),
    path('window/favor/<str:window>/<path:path>', views.favor_window, name='favor_window'),
    
    path('window/meal/<str:cafeteria>/<int:floor>/<str:window>', views.meal_window_detail, name='meal_window_detail'),
    path('window/drink/<str:cafeteria>/<int:floor>/<str:window>', views.drink_window_detail, name='drink_window_detail'),
    path('window/breakfast', views.breakfast_window_detail, name='breakfast_window_detail'),
    path('window/selfselect/<str:window>', views.selfselect_window_detail, name='selfselect_window_detail'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('auth/', include("user.urls")),
    path('blog/', include("myblog.urls")),
    path('cuisine/', include("cuisine.urls")),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'


urlpatterns = [
    path('login', views.mylogin, name='login'),
    path('login/check/<str:email>/<str:password>/<int:remember>', views.check_login, name='check_login'),
    path('logout', views.mylogout, name='logout'),
    path('register', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='email_captcha'),
    path('forget', views.forget, name='forget'),
    path('password', views.send_email_reset, name='reset_password'),
    path('modify', views.modify, name='modify'),
    path('modify_password', views.modify_password, name='modify_password'),
    path('upload_avatar', views.upload_avatar, name='upload_avatar'),
    path('handle_avatar', views.handle_avatar, name='handle_avatar'),
    
    path('center', views.center, name='center'),
    path('history/pub', views.history_pub, name='history_pub'),
    path('history/like', views.history_like, name='history_like'),
    path('history/favorite', views.history_favorite, name='history_favorite'),
    path('history/eaten', views.history_eaten, name='history_eaten'),
    path('history/window', views.history_window, name='history_window'),
]

cuisine/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class Cuisine(models.Model):
    name = models.CharField(max_length=256)
    type = models.CharField(max_length=32)
    cafeteria = models.CharField(max_length=32)
    floor = models.CharField(max_length=32)
    window = models.CharField(max_length=32)
    star_ave = models.FloatField(default=-1)
    cost = models.FloatField(default=-1)
    image = models.ImageField()
    tag1 = models.CharField(max_length=32)
    tag2 = models.CharField(max_length=32)
    tag3 = models.CharField(max_length=32,default='')
    

    def __str__(self):
        return self.name


class CuisineComment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    cuisine = models.ForeignKey(Cuisine, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-pub_time']


class StarCuisine(models.Model):
    star = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cuisine = models.ForeignKey(Cuisine, on_delete=models.CASCADE, related_name='stars')
    created_or_update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_or_update_at']


class FavoriteCuisine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cuisine = models.ForeignKey(Cuisine, on_delete=models.CASCADE, related_name='favorites')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'cuisine')
        ordering = ['-created_at']


class EatenCuisine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cuisine = models.ForeignKey(Cuisine, on_delete=models.CASCADE, related_name='eatens')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'cuisine')
        ordering = ['-created_at']

cuisine/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_GET

import random
import user.models
from .models import Cuisine, CuisineComment, FavoriteCuisine, EatenCuisine, StarCuisine
from user.models import UserDetail
from django.db.models import Q


# Create your views here.
def cuisine_detail(request, cuisine_id):
    cuisine = Cuisine.objects.get(pk=cuisine_id)
    favorite_cuisine = cuisine.favorites.filter(user=request.user).exists()
    eaten_cuisine = cuisine.eatens.filter(user=request.user).exists()
    if 'starNum' in request.GET:
        star = request.GET['starNum']
        starCuisine = StarCuisine.objects.filter(user=request.user, cuisine=cuisine).first()
        if not starCuisine:
            StarCuisine.objects.create(star=star, user=request.user, cuisine=cuisine)
        else:
            starCuisine.star = star
            starCuisine.save()
    mark_stars = StarCuisine.objects.filter(cuisine=cuisine).all()
    star_sum = 0
    for mark_star in mark_stars:
        star_sum += mark_star.star
    if mark_stars.count() == 0:
        cuisine.star_ave = -1
    else:
        cuisine.star_ave = star_sum / mark_stars.count()
    cuisine.save()
    
    context = {
        'cuisine': cuisine,
        'username': request.user.username,
        'favorite_cuisine': favorite_cuisine,
        'eaten_cuisine': eaten_cuisine,
    }
    return render(request, 'cuisine/cuisine_detail.html', context=context)


@require_POST
@login_required()
def pub_comment(request):
    cuisine_id = request.POST.get('cuisine_id')
    content = request.POST.get('content')
    CuisineComment.objects.create(content=content, cuisine_id=cuisine_id, author=request.user)
    return redirect(f'/cuisine/{cuisine_id}')


@require_GET
def search(request):
    # /search?q=xxx
    q = request.GET.get('q')
    cuisines = Cuisine.objects.filter(Q(name__icontains=q)|Q(tag1__exact=q)|Q(tag2__exact=q)|Q(tag3__exact=q)).all()
    context = {
        "cuisines": cuisines,
        'user': request.user,
    }
    return render(request, 'cuisine/cuisine_search.html', context=context)


@login_required
def favor_cuisine(request, cuisine_id):
    cuisine = get_object_or_404(Cuisine, id=cuisine_id)
    favor, created = FavoriteCuisine.objects.get_or_create(user=request.user, cuisine=cuisine)
    if not created:
        favor.delete()
    return redirect(reverse("cuisine:cuisine_detail", kwargs={'cuisine_id': cuisine_id}))


@login_required
def eaten_cuisine(request, cuisine_id):
    cuisine = get_object_or_404(Cuisine, id=cuisine_id)
    eaten, created = EatenCuisine.objects.get_or_create(user=request.user, cuisine=cuisine)
    if not created:
        eaten.delete()
    return redirect(reverse("cuisine:cuisine_detail", kwargs={'cuisine_id': cuisine_id}))


@login_required
def recommend(request):
    user_detail = UserDetail.objects.get(user=request.user)
    weight = user_detail.weight
    height = user_detail.height
    gender = user_detail.gender
    age = user_detail.age
    if height != 0:
        height = float(height) / 100
        bmi = round(weight / (height * height), 2)
    else:
        bmi = -1
    if bmi > 25.0:
        hun_max = 4
        su_max = 2
    elif bmi <= 18.0:
        hun_max = 4
        su_max = 2
    else:
        hun_max = 3
        su_max = 3
    if gender == '男' or gender == '男性':
        hun_max += 1
        su_max -= 1
    else:
        hun_max -= 1
        su_max += 1
    if age >= 60:
        hun_max -= 1
        su_max += 1
    
    cuisines = list(Cuisine.objects.all())
    random.shuffle(cuisines)
    random_skip = random.randint(0,200)
    result = []
    i = 0
    hun_count = 0
    su_count = 0
    sum_count = 0
    for cuisine in cuisines:
        if i > random_skip:
            if (cuisine.tag1 == '素' or cuisine.tag2 == '素' or cuisine.tag3 == '素') \
                    and su_count < su_max and (not cuisine in result):
                result.append(cuisine)
                su_count += 1
                sum_count += 1
            elif (cuisine.tag1 == '荤' or cuisine.tag2 == '荤' or cuisine.tag3 == '荤') \
                    and hun_count < hun_max and (not cuisine in result):
                result.append(cuisine)
                hun_count += 1
                sum_count += 1
        i += 1
        if sum_count == 6:
            break
    context = {
        "bmi": bmi,
        "recommend_cuisines": result,
        "eaten_cuisines": Cuisine.objects.filter(eatens__user=request.user)[:6],
        "favor_cuisines": Cuisine.objects.filter(favorites__user=request.user)[:6],
        "highest_star_cuisines": Cuisine.objects.exclude(star_ave=-1).order_by('-star_ave')[:9],
    }
    return render(request, 'cuisine/cuisine_rec.html', context=context)

templates/cuisine/cuisine_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <title>美食展示</title>
        <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/star.css' %}" media="all" type="text/css"/>
        <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
        <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
        <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #F6F6F6;
            }
            .navbar {
                border-bottom: 1px solid #ddd;
                margin-bottom: 20px;
            }
            .navbar .nav-link {
                font-size: 18px;
                margin-right: 10px;
                transition: color 0.3s, background-color 0.3s;
            }
            .navbar .nav-link:hover {
                color: #262626 !important;
            }
            .navbar .no-hover {
                pointer-events: none;
            }
            .container {
                background-color: #fff;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            }
            .form-control {
                border-radius: 5px;
            }
            .btn-primary {
                background-color: #5091f1;
                border-color: #5091f1;
            }
            .btn-primary:hover {
                background-color: #4078c0;
                border-color: #4078c0;
            }
            .search1 {
                border: 2px solid #ccc;
                border-radius: 10px 0 0 10px;
                height: 50px;
                border-right: none;
            }
            .search-button {
                border: 2px solid #5091f1;
                border-radius: 0 10px 10px 0;
                width: 80px;
                height: 50px;
            }
            .button1 {
                width: 150px;
                padding: 10px;
                background-color: #3975f3;
                color: white;
                border: none;
                border-radius: 3px;
                cursor: pointer;
                font-size: 16px;
            }
            .button1:hover {
                background-color: #2a4bb5;
            }
            .tag {
                display: inline-block;
                background-color: #87CEFA;
                padding: 5px 10px;
                margin-right: 10px;
                border-radius: 5px;
            }
            h2 {
                color: #333;
                font-weight: bold;
            }
            h3 {
                color: #666;
            }
            h4 {
                color: #999;
            }
            span {
                color: #666;
            }
        </style>
    </head>
<body style="background-color: #F6F6F6">
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <img src="{% static 'img/logo.webp' %}" alt="Logo" height="50">
                航味
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cuisine:recommend' %}">菜品推荐</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_eaten' %}">我吃过的</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_favorite' %}">菜品收藏</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_window' %}">窗口收藏</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'cuisine:search' %}" method="GET">
                    <input type="search" name="q" class="form-control" placeholder="输入菜品或标签名称" aria-label="Search">
                </form>
                {% if user.is_authenticated %}
                <div class="text-end">
                    <div class="dropdown"> 
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.userdetail.avatar.url }}" alt="mdo" width="40" height="40" class="rounded-circle">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="{% url 'user:center' %}">个人中心</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <div class="text-end">
                    <a href="{% url 'user:login' %}" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'user:register' %}" class="btn btn-primary">注册</a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

</header>
<div class="row" style="margin-top: 20px">
		<div class="col-md-1" style="margin-right: 40px"></div>
		<div class="col-md-3">
			<img src="{{ cuisine.image.url }}" style="width: 90%" alt="{{ cuisine.name }}">
		</div>
		<div class="col-md-6" style="background-color: white">
			<h2>{{ cuisine.name }}</h2>
			{% if cuisine.cost != -1 %}
				{% if cuisine.window == '卤味' %}
					<span style="font-size: 20px;">
					菜品价格为： {{ cuisine.cost }}元/斤
					</span>
				{% elif cuisine.window == '手工水饺' %}
					<span style="font-size: 20px;">
					菜品价格为： {{ cuisine.cost }}元/两
					</span>
				{% else %}
					<span style="font-size: 20px;">
					菜品价格为： {{ cuisine.cost }}元
					</span>
				{% endif %}
			{% endif %}

			{% if cuisine.type == 'meal' or cuisine.type == 'drink' %}
				<h4 style="margin-top: 20px">位置: {{ cuisine.cafeteria }} {{ cuisine.floor }} {{ cuisine.window }}</h4>
			{% elif cuisine.type == 'selfselect' %}
				<h4 style="margin-top: 20px">做法: {{ cuisine.window }} </h4>
			{% elif cuisine.type == 'breakfast' %}
				<h4 style="margin-top: 20px">位置: 新北一楼/学二一楼 </h4>
			{% endif %}
			
			<div style="margin-top: 20px;display: inline-block;">
			
				<span style="font-size: 20px;">
				<div id="bg">
				<div id="over"></div>
	    </div>
					当前评分: {% if cuisine.star_ave == -1.0 %} 尚未有人进行评分 {% else %} {{ cuisine.star_ave }} {% endif %}
				</span>
				<form style="margin-left:70px;display: inline-block;">
						<input name="starNum" id="starNum" type="hidden"/>
							<span class="starability-container">
								<fieldset class="starability-slot">
									<input type="radio" id="rate_1_0_1_5" name="starLevel" value="5" />
									<label for="rate_1_0_1_5" title="5星"></label>
									<input type="radio" id="rate_1_0_1_4" name="starLevel" value="4" />
									<label for="rate_1_0_1_4" title="4星"></label>
									<input type="radio" id="rate_1_0_1_3" name="starLevel" value="3" />
									<label for="rate_1_0_1_3" title="3星"></label>
									<input type="radio" id="rate_1_0_1_2" name="starLevel" value="2" />
									<label for="rate_1_0_1_2" title="2星"></label>
									<input type="radio" id="rate_1_0_1_1" name="starLevel" value="1" />
									<label for="rate_1_0_1_1" title="1星"></label>
								 </fieldset>
							</span>
							<span style="font-size: 18px;line-height: 2.9rem;padding: 2px;font-style: oblique;" id="starStr"></span>
					<span style="margin-left: 20px">
						<button type="submit" style=" width: 90px;height: 40px" class="btn btn-primary " onclick="evaluation();">确认评分　　　　　
						</button>
					</span>
    		</form>
			</div>
			<div style="margin-top: 20px">
				收藏人数: {{ cuisine.favorites.all|length }}   吃过的人数: {{ cuisine.eatens.all|length }}  评论人数: {{ cuisine.comments.all|length }}
			</div>
			<div style="margin-top: 40px">
            {% if user.is_authenticated %}
            <div style="display: inline-block;">
                {% if favorite_cuisine %}
                    <form action="{% url 'cuisine:favor_cuisine' cuisine.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary" style="margin-left: 20px" type="submit">取消收藏</button>
                    </form>
                {% else %}
                    <form action="{% url 'cuisine:favor_cuisine' cuisine.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary" style="margin-left: 20px" type="submit">收藏</button>
                    </form>
                {% endif %}
            </div>
            
            <div style="display: inline-block;">
                {% if eaten_cuisine %}
                    <form action="{% url 'cuisine:eaten_cuisine' cuisine.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary" style="margin-left: 20px" type="submit">-移除“我吃过的”</button>
                    </form>
                {% else %}
                    <form action="{% url 'cuisine:eaten_cuisine' cuisine.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary" style="margin-left: 20px" type="submit">+加入“我吃过的”</button>
                    </form>
                {% endif %}
            </div>
            
            {% endif %}
			</div>
			<style>
				.tag {
                    display: inline-block;
                    background-color: #87CEEB;
                    color: #fff;
                    padding: 5px 10px;
                    margin-right: 10px;
                    border-radius: 5px;
                    font-size: 14px;
                }
			</style>
			<div style="margin-top: 20px;">
                {% if cuisine.tag1 != '' %}
                    <span class="tag">#{{ cuisine.tag1 }}</span>
                {% endif %}
                {% if cuisine.tag2 != '' %}
                    <span class="tag">#{{ cuisine.tag2 }}</span>
                {% endif %}
                {% if cuisine.tag3 != '' %}
                    <span class="tag">#{{ cuisine.tag3 }}</span>
                {% endif %}
            </div>
		</div>
	</div>
	<div class="mt-2">
        <h3>评论（{{ cuisine.comments.all|length }}）</h3>
        <form id="commentForm" action="{% url 'cuisine:pub_comment' %}" method="POST" onsubmit="return validateComment()">
            {% csrf_token %}
            <input type="hidden" name="cuisine_id" value="{{ cuisine.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content" id="commentContent">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    
    <script>
        function validateComment() {
            var content = document.getElementById("commentContent").value;
            if (content.trim() === "") {
                alert("评论内容不能为空！");
                return false;
            }
            return true;
        }
    </script>
<div class="mt-2">
    <ul class="list-group list-group-flush">
        {% for comment in cuisine.comments.all %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between text-body-secondary">
                    <div class="user-info">
                        <img src="{{ comment.author.userdetail.avatar.url }}" class="rounded-circle" width="40" height="40" alt="">
                        <span class="ms-2">{{ comment.author.username }}</span>
                    </div>
                    <div class="create-time" style="line-height: 40px;">{{ comment.pub_time|date:"Y年m月d日 H时i分" }}</div>
                </div>
                <div class="mt-2">{{ comment.content }}</div>
            </li>
        {% endfor %}
    </ul>
</div>

<script>


	$('[name="starLevel"]').bind("click",function(){
		console.log($(this)[0].value)
		$("#starNum").val($(this)[0].value)
		var starNum = $(this)[0].value;
		if(starNum == 1) $("#starStr").text("差");
		if(starNum == 2) $("#starStr").text("一般");
		if(starNum == 3) $("#starStr").text("良好");
		if(starNum == 4) $("#starStr").text("优秀");
		if(starNum == 5) $("#starStr").text("完美");
	})



	// 提交评论
	function evaluation() {
		//评价等级
		var customerEvaluationLevel = $('#starNum').val();

		if (customerEvaluationLevel == undefined || customerEvaluationLevel == null || customerEvaluationLevel == '') {
			alert('请将满意度选好再提交哦！');
			return false;
		}
	}

    function changeWidth() {
            if ( {{ cuisine.star_ave }} == -1.0){
                var inputValue = 95;
                    }
            else {
                var inputValue = 19 * {{ cuisine.star_ave }};
            }
            var box = document.getElementById('over');
            box.style.width = inputValue + 'px';
        }
    changeWidth()

</script>
</body>
</html>

templates/cuisine/cuisine_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <style>
        .navbar {
            border-bottom: 1px solid #ddd;
            margin-bottom: 20px;
        }
        .navbar .nav-link {
            font-size: 18px;
            margin-right: 10px;
            transition: color 0.3s, background-color 0.3s;
        }
        .navbar .nav-link:hover {
            color: #262626 !important;
        }
        .navbar .no-hover {
            pointer-events: none;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .form-control {
            border-radius: 5px;
        }
        .btn-primary {
            background-color: #5091f1;
            border-color: #5091f1;
        }
        .btn-primary:hover {
            background-color: #4078c0;
            border-color: #4078c0;
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <img src="{% static 'img/logo.webp' %}" alt="Logo" height="50">
                航味
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cuisine:recommend' %}">菜品推荐</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_eaten' %}">我吃过的</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_favorite' %}">菜品收藏</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_window' %}">窗口收藏</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'cuisine:search' %}" method="GET">
                    <input type="search" name="q" class="form-control" placeholder="输入菜品或标签名称" aria-label="Search">
                </form>
                {% if user.is_authenticated %}
                <div class="text-end">
                    <div class="dropdown"> 
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.userdetail.avatar.url }}" alt="mdo" width="40" height="40" class="rounded-circle">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="{% url 'user:center' %}">个人中心</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <div class="text-end">
                    <a href="{% url 'user:login' %}" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'user:register' %}" class="btn btn-primary">注册</a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
</header>
<main class="container">
    <h1 class="text-center my-4">美食集合</h1>
    <div class="row row-cols-2 row-gap-4">
    {% for cuisine in cuisines %}
        <div class="col-md-4">
            <a href="/cuisine/{{ cuisine.id }}" style="text-decoration: none;">
                <div class="card shadow-sm rounded text-center">
                    <div class="card-header" style="background-color: #f8f9fa;">
                        <img src="{{ cuisine.image.url }}" class="card-img-top rounded" alt="{{ cuisine.name }} image">
                    </div>
                    <div class="card-footer" style="background-color: #f8f9fa;">
                        <span style="font-family: '黑体', serif; font-size: 24px; color: #343a40;">{{ cuisine.name }}</span>
                    </div>
                </div>
            </a>
        </div>
        <!-- <div class="col-md-6">
            <div class="card mb-4">
                <img src="{{ cuisine.image.url }}" class="card-img-top" alt="{{ cuisine.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ cuisine.name }}</h5>
                    <a href="/cuisine/{{ cuisine.id }}" class="btn btn-outline-primary">点此跳转{{ cuisine.name }}</a>
                </div>
            </div>
        </div> -->
    {% endfor %}
    </div>
</main>
</body>
</html>