cuisine/urls.py
from django.urls import path
from . import views

app_name = 'cuisine'

urlpatterns = [
    path('<int:cuisine_id>', views.cuisine_detail, name='cuisine_detail'),
    path('pub', views.pub_comment, name='pub_comment'),
    path('search', views.search, name='search'),
    path('favor/<int:cuisine_id>', views.favor_cuisine, name='favor_cuisine'),
    path('eaten/<int:cuisine_id>', views.eaten_cuisine, name='eaten_cuisine'),
    path('recommend', views.recommend, name='recommend'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('map', views.map, name='map'),
    path('window/favor/<str:window>/<path:path>', views.favor_window, name='favor_window'),
    
    path('window/meal/<str:cafeteria>/<int:floor>/<str:window>', views.meal_window_detail, name='meal_window_detail'),
    path('window/drink/<str:cafeteria>/<int:floor>/<str:window>', views.drink_window_detail, name='drink_window_detail'),
    path('window/breakfast', views.breakfast_window_detail, name='breakfast_window_detail'),
    path('window/selfselect/<str:window>', views.selfselect_window_detail, name='selfselect_window_detail'),
]

myblog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('home', views.home, name='home'),
    path('detail/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('like/<int:blog_id>', views.like_blog, name='like_blog'),
    path('pub', views.pub_blog, name='pub_blog'),
    path('comment/pub', views.pub_comment, name='pub_comment'),
    path('search', views.search, name='search'),
    path('delete/<int:blog_id>', views.delete_blog, name='delete'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('auth/', include("user.urls")),
    path('blog/', include("myblog.urls")),
    path('cuisine/', include("cuisine.urls")),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'


urlpatterns = [
    path('login', views.mylogin, name='login'),
    path('login/check/<str:email>/<str:password>/<int:remember>', views.check_login, name='check_login'),
    path('logout', views.mylogout, name='logout'),
    path('register', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='email_captcha'),
    path('forget', views.forget, name='forget'),
    path('password', views.send_email_reset, name='reset_password'),
    path('modify', views.modify, name='modify'),
    path('modify_password', views.modify_password, name='modify_password'),
    path('upload_avatar', views.upload_avatar, name='upload_avatar'),
    path('handle_avatar', views.handle_avatar, name='handle_avatar'),
    
    path('center', views.center, name='center'),
    path('history/pub', views.history_pub, name='history_pub'),
    path('history/like', views.history_like, name='history_like'),
    path('history/favorite', views.history_favorite, name='history_favorite'),
    path('history/eaten', views.history_eaten, name='history_eaten'),
    path('history/window', views.history_window, name='history_window'),
]

user/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class CaptchaModel(models.Model):
    email = models.EmailField(unique=True)
    captcha = models.CharField(max_length=4)
    create_time = models.DateTimeField(auto_now=True)


class UserDetail(models.Model):
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=16, default='不明')
    height = models.IntegerField(default=0)
    weight = models.FloatField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='static/img/avatar/', default='static/img/logo.webp')

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import CaptchaModel

User = get_user_model()


class RegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    captcha = forms.CharField(max_length=4, min_length=4)
    password = forms.CharField()

    def clean_captcha(self):
        captcha = self.cleaned_data.get('captcha')
        email = self.cleaned_data.get('email')

        captcha_model = CaptchaModel.objects.filter(email=email, captcha=captcha).first()
        if not captcha_model:
            raise forms.ValidationError("验证码和邮箱不匹配！")
        captcha_model.delete()
        return captcha


class ResetForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()
    captcha = forms.CharField(max_length=4, min_length=4)


class ModifyForm(forms.Form):
    username = forms.CharField()
    gender = forms.CharField(max_length=16)
    age = forms.IntegerField()
    height = forms.IntegerField()
    weight = forms.FloatField()
    

class ModifyPasswordForm(forms.Form):
    password = forms.CharField()

user/views.py
from django.shortcuts import render, redirect, reverse
from django.http.response import JsonResponse
import string
import random
from django.core.mail import send_mail
from .models import CaptchaModel, UserDetail
from django.views.decorators.http import require_http_methods
from .forms import RegisterForm, ModifyForm, ResetForm, ModifyPasswordForm
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.models import User
from myblog.models import Blog
from cuisine.models import Cuisine
from home.models import FavoriteWindow

User = get_user_model()


@require_http_methods(['GET'])
def mylogin(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')


def check_login(request, email, password, remember):
    user = User.objects.filter(email=email).first()
    if user and user.check_password(password):
        login(request, user)
        if remember == 0:
            request.session.set_expiry(0)
        return JsonResponse({"code": 200})
    elif not user:
        return JsonResponse({"code": 400, "message": '不存在此邮箱！'})
    elif not user.check_password(password):
        return JsonResponse({"code": 400, "message": '密码错误！'})


def mylogout(request):
    logout(request)
    return redirect(reverse('user:login'))


@require_http_methods(['GET', 'POST'])
def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = User.objects.create_user(email=email, username=username, password=password)
            UserDetail.objects.create(user=user)
            return redirect(reverse('user:login'))
        else:
            print(form.errors)
            return redirect(reverse('user:register'))


def send_email_captcha(request):
    email = request.GET.get('email')
    if not email:
        return JsonResponse({"code": 400, "message": '邮箱格式错误！'})
    captcha = "".join(random.sample(string.digits, 4))
    users = User.objects.filter(email=email)
    if not users.exists():
        CaptchaModel.objects.update_or_create(email=email, defaults={'captcha': captcha})
        send_mail("注册验证", message=f"您的注册验证码是：{captcha}", recipient_list=[email], from_email=None)
        return JsonResponse({"code": 200, "message": '验证码发送成功！'})
    else:
        return JsonResponse({"code": 400, "message": '此邮箱已被注册！'})


@require_http_methods(['GET', 'POST'])   
def forget(request):
    if request.method == 'GET':
        return render(request, 'user/forget.html')
    else:
        form = ResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            captcha = form.cleaned_data.get('captcha')
            print(password, captcha)
            c = CaptchaModel.objects.filter(captcha=captcha, email=email).first()
            if not c:
                return redirect(reverse('user:forget'))
            user = User.objects.filter(email=email).first()
            user.set_password(password)
            user.save()
            return redirect(reverse('user:login'))
        else:
            print(form.errors)
            return redirect(reverse('user:forget'))


def send_email_reset(request):
    email = request.GET.get('email')
    if not email:
        return JsonResponse({"code": 400, "message": '邮箱格式错误！'})
    captcha = "".join(random.sample(string.digits, 4))
    users = User.objects.filter(email=email)
    if users.exists():
        CaptchaModel.objects.update_or_create(email=email, defaults={'captcha': captcha})
        send_mail("忘记密码", message=f"您的重置密码验证码是：{captcha}", recipient_list=[email], from_email=None)
        return JsonResponse({"code": 200, "message": '验证码发送成功！'})
    else:
        return JsonResponse({"code": 400, "message": '此邮箱尚未注册！'})


def center(request):
    context = {
        'user': request.user,
    }
    return render(request, 'user/center.html', context=context)


def modify(request):
    if request.method == 'GET':
        context = {
            'user': request.user,
        }
        return render(request, 'user/modify.html', context=context)
    else:
        form = ModifyForm(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            user.username = form.cleaned_data.get('username')
            userdetail = UserDetail.objects.get(user=user)
            userdetail.age = form.cleaned_data.get('age')
            userdetail.gender = form.cleaned_data.get('gender')
            userdetail.height = form.cleaned_data.get('height')
            userdetail.weight = form.cleaned_data.get('weight')
            user.save()
            userdetail.save()
            return redirect(reverse('user:center'))
        else:
            print(form.errors)
            return redirect(reverse('user:center'))


def modify_password(request):
    if request.method == 'GET':
        context = {
            'user': request.user,
        }
        return render(request, 'user/modify_password.html', context=context)
    else:
        form = ModifyPasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.user.id)
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            return redirect(reverse('user:login'))
        else:
            print(form.errors)
            return redirect(reverse('user:center'))


def upload_avatar(request):
    return render(request, 'user/upload_avatar.html')


def handle_avatar(request):
    file = request.FILES.get('avatar')
    user_detail = UserDetail.objects.get(user=request.user)
    user_detail.avatar = file
    user_detail.save()
    return redirect(reverse('user:center'))


def history_pub(request):
    context = {
        'pub_blogs': Blog.objects.filter(author=request.user)
    }
    return render(request, 'user/history_pub.html', context=context)


def history_like(request):
    context = {
        'liked_blogs': Blog.objects.filter(likes__user=request.user)
    }
    return render(request, 'user/history_like.html', context=context)


def history_favorite(request):
    context = {
        'favorite_cuisines': Cuisine.objects.filter(favorites__user=request.user)
    }
    return render(request, 'user/history_favorite.html', context=context)


def history_eaten(request):
    context = {
        'eaten_cuisines': Cuisine.objects.filter(eatens__user=request.user)
    }
    return render(request, 'user/history_eaten.html', context=context)


def history_window(request):
    context = {
        'favorite_windows': FavoriteWindow.objects.filter(user=request.user)
    }
    return render(request, 'user/history_window.html', context=context)
        

templates/user/center.html
<!DOCTYPE html>
<html lang='en'>
<head>
    {% load static %}
    <meta charset='UTF-8'>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>个人中心</title>
    <style>
        body {
            background: #dfdfe1;
        }
        .navbar {
            border-bottom: 1px solid #ddd;
            margin-bottom: 20px;
        }
        .navbar .nav-link {
            font-size: 18px;
            margin-right: 10px;
            transition: color 0.3s, background-color 0.3s;
        }
        .navbar .nav-link:hover {
            color: #262626 !important;
        }
        .navbar .no-hover {
            pointer-events: none;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .form-control {
            border-radius: 5px;
        }
        .btn-primary {
            background-color: #5091f1;
            border-color: #5091f1;
        }
        .btn-primary:hover {
            background-color: #4078c0;
            border-color: #4078c0;
        }
        .head {
            display: flex;
            align-items: center;
            justify-content: center; /* 居中对齐 */
            margin-top: 20px;
        }
        .head img {
            border-radius: 50%;
            width: 150px;
            height: 150px;
            object-fit: cover;
            margin-right: 50px; /* 增加间距 */
        }
        .info {
            font-size: 1.2em;
        }
        .info div {
            margin-bottom: 10px;
        }
        .btn-group {
            margin-top: 20px;
            display: flex;
            gap: 10px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <img src="{% static 'img/logo.webp' %}" alt="Logo" height="50">
                航味
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:modify' %}">修改信息</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:modify_password' %}">修改密码</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:upload_avatar' %}">修改头像</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                <div class="text-end">
                    <div class="dropdown"> 
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.userdetail.avatar.url }}" alt="mdo" width="40" height="40" class="rounded-circle">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="{% url 'user:center' %}">个人中心</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <div class="text-end">
                    <a href="{% url 'user:login' %}" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'user:register' %}" class="btn btn-primary">注册</a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <div id="app" class="container">
        <div class="head">
            <img src="{{ user.userdetail.avatar.url }}" alt="Logo">
            <div class="info">
                <div><strong>名称:</strong> {{ user.username }}</div>
                <div><strong>邮箱:</strong> {{ user.email }}</div>
                <div><strong>上次登录时间:</strong> {{ user.last_login|date:"Y年m月d日 H时i分" }}</div>
                <div><strong>年龄:</strong> {{ user.userdetail.age }} 岁</div>
                <div><strong>性别:</strong> {{ user.userdetail.gender }}</div>
                <div><strong>身高:</strong> {{ user.userdetail.height }} cm</div>
                <div><strong>体重:</strong> {{ user.userdetail.weight }} kg</div>
            </div>
        </div>
        <div class="btn-group">
            <a href="{% url 'user:history_pub' %}" class="btn btn-outline-primary">发布的帖子</a>
            <a href="{% url 'user:history_like' %}" class="btn btn-outline-primary">点赞的帖子</a>
            <a href="{% url 'user:history_eaten' %}" class="btn btn-outline-primary">吃过的美食</a>
            <a href="{% url 'user:history_favorite' %}" class="btn btn-outline-primary">收藏的美食</a>
            <a href="{% url 'user:history_window' %}" class="btn btn-outline-primary">收藏的窗口</a>
        </div>
    </div>
</body>
</html>

templates/user/history_eaten.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>吃过的美食</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    <style>
        body {
            background: #dfdfe1;
        }
        .container {
            margin-top: 50px;
        }
        .card {
            margin-bottom: 20px;
        }
        .card img {
            height: 200px;
            object-fit: cover;
        }
        .empty-message {
            text-align: center;
            margin-top: 50px;
            font-size: 1.2em;
            color: #6c757d;
        }
        .navbar {
            border-bottom: 1px solid #ddd;
            margin-bottom: 20px;
        }
        .navbar .nav-link {
            font-size: 18px;
            margin-right: 10px;
            transition: color 0.3s, background-color 0.3s;
        }
        .navbar .nav-link:hover {
            color: #262626 !important;
            /* font: 1em sans-serif; */
        }
        .navbar .no-hover {
            pointer-events: none;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <img src="{% static 'img/logo.webp' %}" alt="Logo" height="50">
                航味
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cuisine:recommend' %}">菜品推荐</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_eaten' %}">我吃过的</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_favorite' %}">菜品收藏</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_window' %}">窗口收藏</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'cuisine:search' %}" method="GET">
                    <input type="search" name="q" class="form-control" placeholder="输入菜品或标签名称" aria-label="Search">
                </form>
                {% if user.is_authenticated %}
                <div class="text-end">
                    <div class="dropdown"> 
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.userdetail.avatar.url }}" alt="mdo" width="40" height="40" class="rounded-circle">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="{% url 'user:center' %}">个人中心</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <div class="text-end">
                    <a href="{% url 'user:login' %}" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'user:register' %}" class="btn btn-primary">注册</a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        <h1 class="text-center my-4">吃过的美食</h1>
        <div class="row">
            {% for cuisine in eaten_cuisines %}
                <div class="col-md-4">
                    <a href="/cuisine/{{ cuisine.id }}" style="text-decoration: none;">
                        <div class="card shadow-sm rounded text-center">
                            <div class="card-header" style="background-color: #f8f9fa;">
                                <img src="{{ cuisine.image.url }}" class="card-img-top rounded" alt="{{ cuisine.name }} image">
                            </div>
                            <div class="card-footer" style="background-color: #f8f9fa;">
                                <span style="font-family: '黑体', serif; font-size: 24px; color: #343a40;">{{ cuisine.name }}</span>
                            </div>
                        </div>
                    </a>
                </div>
            {% empty %}
                <div class="col-12 empty-message">
                    您尚未吃过任何美食。
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/user/history_favorite.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>收藏的美食</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    <style>
        body {
            background: #dfdfe1;
        }
        .container {
            margin-top: 50px;
        }
        .card {
            margin-bottom: 20px;
        }
        .card img {
            height: 200px;
            object-fit: cover;
        }
        .empty-message {
            text-align: center;
            margin-top: 50px;
            font-size: 1.2em;
            color: #6c757d;
        }
        .navbar {
            border-bottom: 1px solid #ddd;
            margin-bottom: 20px;
        }
        .navbar .nav-link {
            font-size: 18px;
            margin-right: 10px;
            transition: color 0.3s, background-color 0.3s;
        }
        .navbar .nav-link:hover {
            color: #262626 !important;
            /* font: 1em sans-serif; */
        }
        .navbar .no-hover {
            pointer-events: none;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <img src="{% static 'img/logo.webp' %}" alt="Logo" height="50">
                航味
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cuisine:recommend' %}">菜品推荐</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_eaten' %}">我吃过的</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_favorite' %}">菜品收藏</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:history_window' %}">窗口收藏</a>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'cuisine:search' %}" method="GET">
                    <input type="search" name="q" class="form-control" placeholder="输入菜品或标签名称" aria-label="Search">
                </form>
                {% if user.is_authenticated %}
                <div class="text-end">
                    <div class="dropdown"> 
                        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.userdetail.avatar.url }}" alt="mdo" width="40" height="40" class="rounded-circle">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li><a class="dropdown-item" href="{% url 'user:center' %}">个人中心</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <div class="text-end">
                    <a href="{% url 'user:login' %}" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'user:register' %}" class="btn btn-primary">注册</a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        <h1 class="text-center my-4">收藏的美食</h1>
        <div class="row">
            {% for cuisine in favorite_cuisines %}
                <div class="col-md-4">
                    <a href="/cuisine/{{ cuisine.id }}" style="text-decoration: none;">
                        <div class="card shadow-sm rounded text-center">
                            <div class="card-header" style="background-color: #f8f9fa;">
                                <img src="{{ cuisine.image.url }}" class="card-img-top rounded" alt="{{ cuisine.name }} image">
                            </div>
                            <div class="card-footer" style="background-color: #f8f9fa;">
                                <span style="font-family: '黑体', serif; font-size: 24px; color: #343a40;">{{ cuisine.name }}</span>
                            </div>
                        </div>
                    </a>
                </div>
            
            {% empty %}
                <div class="col-12 empty-message">
                    您尚未收藏过任何美食。
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
  <meta charset="utf-8">
  <title>登录</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #dfdfe1 !important;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }
    .login-container {
      background-color: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      width: 300px;
      height: 500px;
    }
    .login-container h2 {
      margin-bottom: 20px;
        font-family: 黑体, serif;
    }
    .login-container .input-group1 {
      width: calc(100% - 20px);
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ddd;
      border-radius: 3px;
      font-size: 16px;
    }

    .login-container button {
      width: 100%;
      padding: 10px;
      background-color: #3975f3;
      color: white;
      border: none;
      border-radius: 3px;
      cursor: pointer;
      font-size: 16px;
    }
    .login-container button:hover {
      background-color: #2a4bb5;
    }
  </style>
  <link rel="stylesheet" href="{% static '/plugins/bootstrap-5.3.0-alpha1-dist/css/bootstrap.css' %}">
</head>
<body>
  <div class="login-container">
		<div>
			<img src="{% static 'img/logo.webp' %}" class="brand-logo" alt="" height="50">
			<span style="font-size: 20px; color: grey"> The Taste of BUAA </span>
	  </div>
    <h2 style="text-align: center">欢迎登录</h2>
		<br>
    <form action="" method="post" style="text-align: center">
			{% csrf_token %}
      <input type="text" class="input-group1" id="email" name="email" placeholder="邮箱">
      <br>
      <input type="password" class="input-group1" id="password" name="password" placeholder="密码">
      <br>
			<br>
			<div>
				<div class="form-check mb-3" style="text-align: left">
					<input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
					<span style="margin-right: 100px">记住我 </span>
					<span style="text-align: right ">
						<a href="{% url 'user:forget' %}" class="auth-link text-black" >忘记密码?</a>
					</span>
				</div>
			</div>
      <button type="submit" id="login">登录</button>
    </form>
		<div class="text-center mt-4 font-weight-light">
                  还未拥有账号？点击 <a href="{% url 'user:register' %}" class="text-primary">注册</a>
    </div>
  </div>
</body>
</html>